### ISSUE TITLE
UTF-8 issue?

### ISSUE THREAD

**Issue by xme** [gr4ym4ntx/attackintel#7]
Description:
Traceback (most recent call last):
  File "attackintel.py", line 203, in <module>
    attackintel().main()
  File "attackintel.py", line 201, in main
    self.prt2screen(group_name,alias_arr,tech_json,tech_id_array,tech_name_array)
  File "attackintel.py", line 106, in prt2screen
    print (t_json[idx]['query']['results'][t_id_array[idx]]['printouts']['Has technical description'][0] + "\n")
UnicodeEncodeError: 'ascii' codec can't encode character '\xa0' in position 223: ordinal not in range(128)

**Comment by gr4ym4ntx** [comment]
hmmm. which entry was this for?

**Comment by xme** [comment]
Just launched the script, select threatlist 01 (Axiom, Group 72):

******************************* Technique/T1003: Credential Dumping *******************************

Tactic:
Credential Access

Description:
Traceback (most recent call last):
  File "attackintel.py", line 203, in <module>
    attackintel().main()
  File "attackintel.py", line 201, in main
    self.prt2screen(group_name,alias_arr,tech_json,tech_id_array,tech_name_array)
  File "attackintel.py", line 106, in prt2screen
    print (t_json[idx]['query']['results'][t_id_array[idx]]['printouts']['Has technical description'][0] + "\n")
UnicodeEncodeError: 'ascii' codec can't encode character '\xa0' in position 223: ordinal not in range(128)
